### ISSUE TITLE
固定端口感觉不是很方便，建议改成用配置文件控制

### ISSUE THREAD

**Issue by Eggwardhan** [lipku/metahuman-stream#186]
rt

**Comment by lipku** [comment]
这个是srs的配置，srs docker运行的参数可以改端口映射

**Comment by Eggwardhan** [comment]
我的意思是，例如web 页面的template等端口8000啥的都是都是写死的

**Comment by zhjunqin** [comment]
docker 启动的时候主机的端口换了，该改哪些代码？比如 8080 换成 8181

**Comment by ZyairYH** [comment]
需要改docker的 conf/rtc.conf 文件
先启动一个容器把里面的 rtc.conf文件复制一份出来
然后修改配置 比如把8000->16800
```
# WebRTC streaming config for SRS.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
}
rtc_server {
    enabled on;
    listen 16800; # UDP port
    # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#config-candidate
    candidate $CANDIDATE;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc off;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp off;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}
```

docker 启动的时候 挂载这个新的配置文件到容器里 然后指定加载新配置文件启动 我用的时docker  compose方法

```yaml
  livetalking-srs:
    image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5
    container_name: fastgpt-ricoh-product-livetalking-srs
    ports:
      - "16935:1935"
      - "16080:8080"
      - "16985:1985"
      - "16800:16800/udp"
    environment:
      - CANDIDATE=xxxx
    volumes:
      - ./rtc.conf:/usr/local/srs/conf/myrtc.conf
    command: objs/srs -c conf/myrtc.conf
```



> 我的意思是，例如web 页面的template等端口8000啥的都是都是写死的
